FROM php:8.2-fpm-alpine

# Instalar extensiones necesarias para Laravel
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        libpq-dev \
        libonig-dev \
        libxml2-dev \
        libzip-dev \
        zip \
        unzip \
        git \
        curl; \
    \
    # Extensiones PHP necesarias
    docker-php-ext-install \
        pdo_pgsql \
        mbstring \
        xml \
        bcmath \
        zip \
        opcache; \
    \
    # Redis
    pecl install redis && docker-php-ext-enable redis; \
    \
    # Limpiar
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

# Composer (forma correcta)
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Permisos correctos para Laravel
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache

USER www-data