server {
    listen 80;
    server_name localhost;

    # Maestro C# (Root)
    location / {
        proxy_pass http://localhost:5225;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Laravel PHP
    location /php-app/ {
        rewrite ^/php-app/(.*)$ /$1 break;
        fastcgi_pass php-service:9000;
        include fastcgi_params;
        # Importante: Esta ruta debe coincidir con la interna del contenedor PHP
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
    }
}