services:
  php-service:
    build:
        context: .
        dockerfile: ./services/laravel/Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ../src/php-app:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    command:
      - sh
      - -lc
      - |
        php -r 'while(!@fsockopen("pgsql",5432)){echo "Esperando a Postgres...\n";sleep(1);}';
        composer install --no-interaction --prefer-dist --optimize-autoloader;
        if ! grep -q '^APP_KEY=base64:' .env; then
          php artisan key:generate --force --no-interaction;
        fi;
        php artisan migrate --force --no-interaction;
        php-fpm -F
    networks:
      - app-network

  fastapi-service:
    build:
      context: .
      dockerfile: ./services/fastapi/dockerfile
    volumes:
      - ../src/fastapi:/app
    environment:
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET=${MINIO_BUCKET}
    ports:
      - "8000:8000"  
    networks:
      - app-network

networks:
  app-network:
    external: true