server {
    listen 80;
    server_name localhost;

    # Backend C#
    location / {
        proxy_pass http://dotnet-service:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Laravel App
    location /php-app {
       alias /var/www/html/public; # Aquí le decimos "esta subruta vive aquí"
        index index.php;
        try_files $uri $uri/ @laravel;

        # Procesador de PHP
        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass php-service:9000;
            include fastcgi_params;
            
            # CRUCIAL: SCRIPT_FILENAME debe ser la ruta absoluta al index.php
            # No uses $document_root aquí porque con 'alias' a veces falla
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        }
    }

    # Esto maneja las rutas internas de Laravel (ej: /php-app/login)
    location @laravel {
        rewrite /php-app/(.*)$ /php-app/index.php?/$1 last;
    }
}