// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NormaQ.Data;

#nullable disable

namespace NormaQ.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609224138_EditVwDouments")]
    partial class EditVwDouments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NormaQ.Models.ActividadSemanalView", b =>
                {
                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InicioSemana")
                        .HasColumnType("datetime2");

                    b.Property<int>("Semana")
                        .HasColumnType("int");

                    b.Property<int>("VersionesAprobadas")
                        .HasColumnType("int");

                    b.Property<int>("VersionesCreadas")
                        .HasColumnType("int");

                    b.Property<int>("VersionesRechazadas")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_Actividad_Semanal", (string)null);
                });

            modelBuilder.Entity("NormaQ.Models.Compania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Rfc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rfc");

                    b.HasKey("Id")
                        .HasName("PK__Compania__3213E83F952175FC");

                    b.ToTable("Companias");
                });

            modelBuilder.Entity("NormaQ.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("CompaniaId")
                        .HasColumnType("int")
                        .HasColumnName("compania_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__Departam__3213E83F82742017");

                    b.HasIndex("CompaniaId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("NormaQ.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("creado_por");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int")
                        .HasColumnName("departamento_id");

                    b.Property<int>("NivelId")
                        .HasColumnType("int")
                        .HasColumnName("nivel_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombre");

                    b.Property<int>("NormaId")
                        .HasColumnType("int")
                        .HasColumnName("norma_id");

                    b.HasKey("Id")
                        .HasName("PK__Document__3213E83FCE9B336E");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("NivelId");

                    b.HasIndex("NormaId");

                    b.HasIndex(new[] { "DepartamentoId" }, "IX_Documentos_Depto");

                    b.HasIndex(new[] { "Codigo" }, "UQ_Documentos_Codigo")
                        .IsUnique();

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("NormaQ.Models.DocumentoAprobadoView", b =>
                {
                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("approved_by");

                    b.Property<string>("CodigoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("codigo_documento");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("departamento");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int")
                        .HasColumnName("documento_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nivel");

                    b.Property<string>("NombreDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre_documento");

                    b.Property<string>("NormaCodigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("norma_codigo");

                    b.Property<string>("NormaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("norma_nombre");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("owner");

                    b.Property<string>("StoragePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("storage_path");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("version");

                    b.Property<int>("VersionId")
                        .HasColumnType("int")
                        .HasColumnName("version_id");

                    b.ToTable((string)null);

                    b.ToView("vw_Documentos_Aprobados", (string)null);
                });

            modelBuilder.Entity("NormaQ.Models.DocumentosMasVersionesView", b =>
                {
                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalVersiones")
                        .HasColumnType("int");

                    b.Property<int>("VersionesAprobadas")
                        .HasColumnType("int");

                    b.Property<int>("VersionesConRechazo")
                        .HasColumnType("int");

                    b.Property<int>("VersionesObsoletas")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_Documentos_Mas_Versiones", (string)null);
                });

            modelBuilder.Entity("NormaQ.Models.FirmasPendientesView", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentoCodigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoFirma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VersionCreadaEn")
                        .HasColumnType("datetime2");

                    b.ToTable((string)null);

                    b.ToView("vw_Firmas_Pendientes", (string)null);
                });

            modelBuilder.Entity("NormaQ.Models.FlujosAprobacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comentarios");

                    b.Property<string>("EstadoFirma")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado_firma");

                    b.Property<DateTime?>("FechaFirma")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_firma");

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint")
                        .HasColumnName("orden");

                    b.Property<string>("TipoFirma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_firma");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<int>("VersionId")
                        .HasColumnType("int")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("PK__Flujos_A__3213E83FC1B62FB2");

                    b.HasIndex("VersionId");

                    b.HasIndex(new[] { "UsuarioId", "EstadoFirma" }, "IX_Flujos_UsuarioEstado");

                    b.ToTable("Flujos_Aprobacion", null, t =>
                        {
                            t.HasTrigger("trg_MutarEstadoVersion");

                            t.HasCheckConstraint("CHK_Flujos_Estado", "estado_firma IN ('Pendiente', 'Aprobado', 'Rechazado', 'Cancelado')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NormaQ.Models.NivelesDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.Property<byte>("Numero")
                        .HasColumnType("tinyint")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("PK__Niveles___3213E83F2B73C355");

                    b.HasIndex(new[] { "Numero" }, "UQ_Niveles_Numero")
                        .IsUnique();

                    b.ToTable("Niveles_Documento", (string)null);
                });

            modelBuilder.Entity("NormaQ.Models.Norma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("PK__Normas__3213E83F4A76CF67");

                    b.HasIndex(new[] { "Codigo" }, "UQ_Normas_Codigo")
                        .IsUnique();

                    b.ToTable("Normas");
                });

            modelBuilder.Entity("NormaQ.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3213E83FAFCD81BD");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NormaQ.Models.SecuenciaFirma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int")
                        .HasColumnName("documento_id");

                    b.Property<byte>("Orden")
                        .HasColumnType("tinyint")
                        .HasColumnName("orden");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<string>("TipoFirma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_firma");

                    b.HasKey("Id")
                        .HasName("PK__Secuenci__3213E83FD0E8379F");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "DocumentoId", "Orden" }, "UQ_SecFirma_Orden")
                        .IsUnique();

                    b.ToTable("Secuencia_Firma", (string)null);
                });

            modelBuilder.Entity("NormaQ.Models.SnapshotDeptoView", b =>
                {
                    b.Property<int>("Aprobados")
                        .HasColumnType("int");

                    b.Property<int>("Borradores")
                        .HasColumnType("int");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<int>("EnRevision")
                        .HasColumnType("int");

                    b.Property<int>("Obsoletos")
                        .HasColumnType("int");

                    b.Property<int>("TotalVersiones")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_Snapshot_Depto", (string)null);
                });

            modelBuilder.Entity("NormaQ.Models.SolicitudesRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_solicitud")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.HasKey("Id")
                        .HasName("PK_Solicitudes_Registro");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Solicitudes_Registro_Email");

                    b.HasIndex("RolId");

                    b.ToTable("Solicitudes_Registro", (string)null);
                });

            modelBuilder.Entity("NormaQ.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3213E83F893CFD1F");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex(new[] { "Email" }, "UQ_Usuarios_Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("NormaQ.Models.UsuariosActivosView", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<int>("FirmasAprobadas")
                        .HasColumnType("int");

                    b.Property<int>("FirmasRechazadas")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalFirmas")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaFirma")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_Usuarios_Activos", (string)null);
                });

            modelBuilder.Entity("NormaQ.Models.UsuariosRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int")
                        .HasColumnName("departamento_id");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3213E83F11B0C0F4");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "UsuarioId", "RolId", "DepartamentoId" }, "UQ_UsuariosRoles")
                        .IsUnique();

                    b.ToTable("Usuarios_Roles", (string)null);
                });

            modelBuilder.Entity("NormaQ.Models.VersionesDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int")
                        .HasColumnName("creado_por");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int")
                        .HasColumnName("documento_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Borrador")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaObsolescencia")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_obsolescencia");

                    b.Property<string>("MinioIdentifier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("minio_identifier");

                    b.Property<byte>("VersionMayor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("version_mayor");

                    b.Property<byte>("VersionMenor")
                        .HasColumnType("tinyint")
                        .HasColumnName("version_menor");

                    b.HasKey("Id")
                        .HasName("PK__Versione__3213E83FE6E0D886");

                    b.HasIndex("CreadoPor");

                    b.HasIndex(new[] { "Estado" }, "IX_Versiones_Estado");

                    b.HasIndex(new[] { "DocumentoId", "VersionMayor", "VersionMenor" }, "UQ_Versiones_Numero")
                        .IsUnique();

                    b.ToTable("Versiones_Documento", (string)null);
                });

            modelBuilder.Entity("NormaQ.Models.Departamento", b =>
                {
                    b.HasOne("NormaQ.Models.Compania", "Compania")
                        .WithMany("Departamentos")
                        .HasForeignKey("CompaniaId")
                        .IsRequired()
                        .HasConstraintName("FK_Deptos_Companias");

                    b.Navigation("Compania");
                });

            modelBuilder.Entity("NormaQ.Models.Documento", b =>
                {
                    b.HasOne("NormaQ.Models.Usuario", "CreadoPorNavigation")
                        .WithMany("Documentos")
                        .HasForeignKey("CreadoPor")
                        .IsRequired()
                        .HasConstraintName("FK_Docs_Creador");

                    b.HasOne("NormaQ.Models.Departamento", "Departamento")
                        .WithMany("Documentos")
                        .HasForeignKey("DepartamentoId")
                        .IsRequired()
                        .HasConstraintName("FK_Docs_Depto");

                    b.HasOne("NormaQ.Models.NivelesDocumento", "Nivel")
                        .WithMany("Documentos")
                        .HasForeignKey("NivelId")
                        .IsRequired()
                        .HasConstraintName("FK_Docs_Nivel");

                    b.HasOne("NormaQ.Models.Norma", "Norma")
                        .WithMany("Documentos")
                        .HasForeignKey("NormaId")
                        .IsRequired()
                        .HasConstraintName("FK_Docs_Norma");

                    b.Navigation("CreadoPorNavigation");

                    b.Navigation("Departamento");

                    b.Navigation("Nivel");

                    b.Navigation("Norma");
                });

            modelBuilder.Entity("NormaQ.Models.FlujosAprobacion", b =>
                {
                    b.HasOne("NormaQ.Models.Usuario", "Usuario")
                        .WithMany("FlujosAprobacions")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Flujos_Usuario");

                    b.HasOne("NormaQ.Models.VersionesDocumento", "Version")
                        .WithMany("FlujosAprobacions")
                        .HasForeignKey("VersionId")
                        .IsRequired()
                        .HasConstraintName("FK_Flujos_Version");

                    b.Navigation("Usuario");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NormaQ.Models.SecuenciaFirma", b =>
                {
                    b.HasOne("NormaQ.Models.Documento", "Documento")
                        .WithMany("SecuenciaFirmas")
                        .HasForeignKey("DocumentoId")
                        .IsRequired()
                        .HasConstraintName("FK_SecFirma_Doc");

                    b.HasOne("NormaQ.Models.Role", "Rol")
                        .WithMany("SecuenciaFirmas")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_SecFirma_Rol");

                    b.Navigation("Documento");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("NormaQ.Models.SolicitudesRegistro", b =>
                {
                    b.HasOne("NormaQ.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .IsRequired()
                        .HasConstraintName("FK_Solicitudes_Departamentos");

                    b.HasOne("NormaQ.Models.Role", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_Solicitudes_Roles");

                    b.Navigation("Departamento");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("NormaQ.Models.Usuario", b =>
                {
                    b.HasOne("NormaQ.Models.Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Deptos");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("NormaQ.Models.UsuariosRole", b =>
                {
                    b.HasOne("NormaQ.Models.Departamento", "Departamento")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("DepartamentoId")
                        .IsRequired()
                        .HasConstraintName("FK_UsuRoles_Depto");

                    b.HasOne("NormaQ.Models.Role", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_UsuRoles_Rol");

                    b.HasOne("NormaQ.Models.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_UsuRoles_Usuario");

                    b.Navigation("Departamento");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NormaQ.Models.VersionesDocumento", b =>
                {
                    b.HasOne("NormaQ.Models.Usuario", "CreadoPorNavigation")
                        .WithMany("VersionesDocumentos")
                        .HasForeignKey("CreadoPor")
                        .IsRequired()
                        .HasConstraintName("FK_Ver_Creador");

                    b.HasOne("NormaQ.Models.Documento", "Documento")
                        .WithMany("VersionesDocumentos")
                        .HasForeignKey("DocumentoId")
                        .IsRequired()
                        .HasConstraintName("FK_Ver_Documento");

                    b.Navigation("CreadoPorNavigation");

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("NormaQ.Models.Compania", b =>
                {
                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("NormaQ.Models.Departamento", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Usuarios");

                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("NormaQ.Models.Documento", b =>
                {
                    b.Navigation("SecuenciaFirmas");

                    b.Navigation("VersionesDocumentos");
                });

            modelBuilder.Entity("NormaQ.Models.NivelesDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("NormaQ.Models.Norma", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("NormaQ.Models.Role", b =>
                {
                    b.Navigation("SecuenciaFirmas");

                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("NormaQ.Models.Usuario", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("FlujosAprobacions");

                    b.Navigation("UsuariosRoles");

                    b.Navigation("VersionesDocumentos");
                });

            modelBuilder.Entity("NormaQ.Models.VersionesDocumento", b =>
                {
                    b.Navigation("FlujosAprobacions");
                });
#pragma warning restore 612, 618
        }
    }
}
